version: '3.9'

services:
  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - '5498:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/create_tables.sql
